### Funciones en Python

In [1]:
import time
from math import sqrt

In [5]:
# 1+1

In [40]:
def suma(a,b,c=10):
    # Operaciones 
    doble = 2*a
    triple = 3*b
    ocho = 8*c

    print(ocho)

    return doble + triple + ocho 

In [41]:
suma(1,2, 20) #1,2,10

160


168

In [4]:
def saludar(nombre):
    return f"Hola, {nombre}!"

print(saludar("Ximena"))

Hola, Ximena!


In [11]:
def dividir(dividendo, divisor):
    cociente = dividendo // divisor
    resto = dividendo % divisor
    return cociente, resto

resultado = dividir(10, 3)
print(resultado)
cociente, resto = dividir(10, 3)
print(cociente, resto)

(3, 1)
3 1


In [12]:
def mostrar_args_kwargs(*args, **kwargs):
    print("Args:", args)
    print("Kwargs:", kwargs)

mostrar_args_kwargs(1, 2, 3, a=10, b=20, c = 30)

Args: (1, 2, 3)
Kwargs: {'a': 10, 'b': 20, 'c': 30}


In [13]:
def es_primo(n):

  if(n==1):
    return False

  for i in range(2,n):
    if(n % i == 0):
      return False
  
  return True

In [17]:
es_primo(12)

False

In [14]:
es_primo(29996224275833)

KeyboardInterrupt: 

In [18]:
def es_primo_rapido(n):

  if(n==1):
    return False

  for i in range(2,int(sqrt(n) + 1)):
    if(n % i == 0):
      return False

  return True

In [22]:
es_primo_rapido(54)

False

In [34]:
sqrt(29996224275833)

5476880.889323138

In [33]:
es_primo_rapido(29996224275833)

True

# Recursividad

In [35]:
def factorial(n):
    if n < 0:
        raise ValueError("El número debe ser no negativo")
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

print(factorial(5))

120


In [43]:
factorial(10000000)

RecursionError: maximum recursion depth exceeded

In [44]:
def fibonacci(n):
  # Esta función regresa el n-ésimo término de Fibonacci

  if(n==1):
    return 0
  elif(n==2):
    return 1
  else:
    return fibonacci(n-1) + fibonacci(n-2)

In [45]:
fibonacci(7)

8

In [46]:
import time

In [51]:
inicio = time.time()
numero = fibonacci(40)
fin = time.time()

print(f'El termino de fibonacci calculado es {numero}')
print(fin - inicio)

El termino de fibonacci calculado es 63245986
9.042293548583984


# Funciones lambda

In [53]:
function_lambda = lambda x: x * 10
print(function_lambda(5))  # Output: 10

50


In [54]:
sumar = lambda a, b: a + b
print(sumar(3, 4))  # Output: 7

7


In [55]:
numeros = [1, 2, 3, 4]
cuadrados = list(map(lambda x: x ** 2, numeros))
print(cuadrados)

[1, 4, 9, 16]


In [56]:
numeros = [1, 2, 3, 4, 5, 6]
pares = list(filter(lambda x: x % 2 == 0, numeros))
print(pares)

[2, 4, 6]


# Algo más complicado

In [ ]:
def burbuja(lista):
    n = len(lista)
    for i in range(n):
        for j in range(0, n - i - 1):
            if lista[j] > lista[j + 1]:
                # Intercambiar los elementos si están en el orden incorrecto
                lista[j], lista[j + 1] = lista[j + 1], lista[j]
    return lista

# Ejemplo de uso
numeros = [5, 3, 8, 4, 2]
print("Lista original:", numeros)
ordenada = burbuja(numeros.copy())
print("Lista ordenada:", ordenada)

### Ejercicios

1. Escribe una función que permita convertir de grados Fahrenheit a Celsius y viceversa.

2. Escribe una función que, dada una lista de números, regrese la distancia mínima y máxima entre los números dentro de esa lista.

2. Escribe una función que dada una cadena de caracteres regrese un diccionario que contenga el número de veces que aparece cada caracter. (Ejemplo, 'AABC' debe regresar {'A':2, 'B': 1, 'C':1})

# Programación orientada a objetos

In [2]:
valor = 5
valor_2 = 10

In [14]:
cadena = 'Biomedica'

In [15]:
cadena.lower()

'biomedica'

In [ ]:
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def saludar(self):
        return f"Hola, me llamo {self.nombre} y tengo {self.edad} años."

In [8]:
# Uso
persona_1 = Persona("Andres", 30)

In [13]:
persona_1.saludar()

'Hola, me llamo Andres y tengo 30 años.'

### Atributos e instancias de una clase

Una primera clase

In [29]:
class CuentaBancaria:
    def __init__(self, titular='Sixto', saldo=0):
        self.titular = titular
        self.saldo = saldo

    def depositar(self, cantidad):
        self.saldo += cantidad

    def retirar(self, cantidad):
        if cantidad <= self.saldo:
            self.saldo -= cantidad
        else:
            print("Fondos insuficientes.")

    def mostrar_saldo(self):
        return f"Saldo de {self.titular}: {self.saldo}"

In [33]:
# Uso
cuenta = CuentaBancaria('David', 1000000)

In [35]:
cuenta.saldo

1000000

In [36]:
cuenta.depositar(1000)

In [37]:
cuenta.saldo

1001000

In [39]:
cuenta.retirar(5000)
print(cuenta.mostrar_saldo())

Saldo de David: 996000


Atributos de instancia y clase

In [44]:
class Persona:
    # Atributo de clase (compartido entre todas las instancias)
    especie = "Homo sapiens"
    lugar = "Sistema Solar"
    
    def __init__(self, nombre, edad):
        # Atributos de instancia (específicos de cada objeto)
        self.nombre = nombre
        self.edad = edad

    def presentar(self):
        # Método que accede a atributos de instancia
        print(f"Hola, mi nombre es {self.nombre} y tengo {self.edad} años.")


In [42]:
persona_1 = Persona('Miguel', 40)

In [45]:
Persona.lugar

'Sistema Solar'

In [19]:
class SecuenciaGenomica:
    def __init__(self, cadena):
        self.cadena = cadena

    def longitud(self):
        return len(self.cadena)
    
    def complemento(self):
        secuencia_complemento = ""

        for nucleotido in self.cadena:
            if(nucleotido == "A"):
                secuencia_complemento += "T"
            elif(nucleotido == "T"):
                secuencia_complemento += "A"

            # Modificar función para que dé el complemento correcto
            else:
                secuencia_complemento += "0"
        return secuencia_complemento
                
cadena = SecuenciaGenomica("ATCGGATTA")
print(cadena.complemento())

TA000TAAT


In [ ]:
cadena = SecuenciaGenomica("ATCGGATTA")
cadena.complemento()

'TA000TAAT'

In [50]:
# Crear instancias
persona1 = Persona("Carlos", 30)
persona2 = Persona("Carlos", 30)

# Llamada a métodos
persona1.presentar()
persona2.presentar()

Hola, mi nombre es Carlos y tengo 30 años.
Hola, mi nombre es Carlos y tengo 30 años.


In [51]:
persona1 == persona2

False

Ejemplo de atributo de instancia

In [18]:
persona1.nombre

'Carlos'

Ejemplo de atributo de clase

In [17]:
Persona.especie

'Homo sapiens'

Método de clase

In [54]:
class Carro:
    # Atributo de clase
    marca = "Toyota"

    def __init__(self, modelo, color):
        self.modelo = modelo
        self.color = color

    @classmethod
    def cambiar_marca(cls, nueva_marca):
        cls.marca = nueva_marca
        print(f"Marca cambiada a {cls.marca}")

In [56]:
# Crear una instancia
mi_carro = Carro("Fusion", "Rojo")

In [57]:
# Llamar al método de clase para cambiar la marca
Carro.cambiar_marca("Ford")

# Verificar el cambio de marca
print(f"La marca del carro es ahora: {mi_carro.marca}")

Marca cambiada a Ford
La marca del carro es ahora: Ford


In [66]:
mi_carro = Carro("Camry", "Rojo")
mi_carro_2 = Carro("Corolla", "Azul")

Métodos especiales

In [78]:
punto = Punto(3,5)
punto_2 = Punto(4,7)

In [79]:
print(punto)

Punto(3, 5)


In [80]:
punto + punto_2

Punto(7, 12)

In [77]:
class Punto:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    # Método para la representación del objeto

    # Como representar el objeto con la funcion print
    def __repr__(self):
        return f"Punto({self.x}, {self.y})"

    # Método para sumar puntos
    # Como operar con el signo "+" dos puntos
    def __add__(self, otro_punto):
        return Punto(self.x + otro_punto.x, self.y + otro_punto.y)


In [26]:
# Crear dos instancias de Punto
punto1 = Punto(2, 3)
punto2 = Punto(5, 7)

# Sumar los puntos
resultado = punto1 + punto2
print(resultado)  

Punto(7, 10)


### Ejercicio

1. Construye una clase cuyo objeto sea un vector en $\mathbb{R}^n$ ($n$ siendo cualquier entero positivo). Implementa las operaciones de suma, resta, producto punto y producto de Hadamard entre vectores.

2. Construye una clase cuyo objeto sean secuencias genómicas, esto es, cuyo objeto sea una secuencia del tipo "AGTCAAGTAA". Añade los métodos y atributos que consideres. Posibles métodos: cálculo de la longitud de la secuencia, cálculo de ocurrencia de cada uno de los nucleótidos, producir el complemento de la cadena, generar el complemento inverso.

# Ejemplos con Numpy

In [82]:
import numpy as np

In [84]:
type(a)

numpy.ndarray

In [88]:
a+b

array([2, 4, 6])

In [87]:
# Crear un array desde una lista
a = np.array([1, 2, 3])
print("Array 1D:", a)

# Crear un array 2D (matriz)
b = np.array([1, 2,3])

Array 1D: [1 2 3]


In [95]:
s = b'hello world'

np.frombuffer(s, dtype='S1', count=5, offset=6)
np.array([b'w', b'o', b'r', b'l', b'd'], dtype='|S1')

array([b'w', b'o', b'r', b'l', b'd'], dtype='|S1')

In [91]:

# Crear arrays de ceros, unos, o valores aleatorios
print("Zeros:\n", np.zeros((4, 3)))
print("Ones:\n", np.ones((2, 3)))
print("Random:\n", np.random.rand(2, 3))

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Random:
 [[0.30262764 0.92750056 0.50889673]
 [0.14818181 0.73285266 0.10133521]]


In [97]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", a.shape)     # (2, 3)
print("Size:", a.size)       # 6
print("Dimensiones:", a.ndim)  # 2
print("Tipo de datos:", a.dtype)  # int64 (por ejemplo)

Shape: (2, 3)
Size: 6
Dimensiones: 2
Tipo de datos: int32


In [98]:
a = np.array([[10, 20, 30], [40, 50, 60]])

print(a[0, 1])    # Accede al elemento en fila 0, columna 1 → 20
print(a[:, 1])    # Accede a toda la columna 1 → [20 50]
print(a[1, :])    # Accede a toda la fila 1 → [40 50 60]
print(a[0:2, 1:]) # Submatriz → [[20 30], [50 60]]

20
[20 50]
[40 50 60]
[[20 30]
 [50 60]]


In [99]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("Suma:", a + b)       # [11 22 33]
print("Multiplicación:", a * b)  # [10 40 90]
print("Potencia:", a ** 2)  # [1 4 9]
print("Seno:", np.sin(a))   # Seno de cada elemento

Suma: [11 22 33]
Multiplicación: [10 40 90]
Potencia: [1 4 9]
Seno: [0.84147098 0.90929743 0.14112001]


In [38]:
data = np.array([[1, 2], [3, 4]])

print("Máximo:", np.max(data))       # 4
print("Mínimo:", np.min(data))       # 1
print("Promedio:", np.mean(data))    # 2.5
print("Desviación estándar:", np.std(data))  # ~1.118

Máximo: 4
Mínimo: 1
Promedio: 2.5
Desviación estándar: 1.118033988749895


In [40]:
print("Suma por filas:", np.sum(data, axis=1))
print("Suma por columnas:", np.sum(data, axis=0))

Suma por filas: [3 7]
Suma por columnas: [4 6]


In [35]:
from numpy.linalg import inv, det

A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

In [36]:
print(A)

[[1 2]
 [3 4]]


In [37]:
# Multiplicación de matrices
print("A @ B:\n", A @ B)

# Determinante
print("Determinante de A:", det(A))  # -2.0

# Inversa de una matriz
print("Inversa de A:\n", inv(A))

A @ B:
 [[ 4  4]
 [10  8]]
Determinante de A: -2.0000000000000004
Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


¿Dónde puedo ver más sobre los métodos y funciones de la librería Numpy? En la documentación oficial.

Otra librería: random

In [1]:
import random

In [11]:
frutas = ['manzana', 'banana', 'naranja', 'pera']
fruta_aleatoria = random.choice(frutas)
print(f"Fruta aleatoria: {fruta_aleatoria}")

Fruta aleatoria: manzana


In [10]:
numero = random.randint(1, 100)
print(f"Número aleatorio entre 1 y 100: {numero}")

Número aleatorio entre 1 y 100: 30


In [9]:
decimal = random.uniform(1.5, 5.5)
print(f"Número decimal aleatorio entre 1.5 y 5.5: {decimal}")

Número decimal aleatorio entre 1.5 y 5.5: 1.8747809594463698


In [8]:
numeros = list(range(1, 50))
seleccionados = random.sample(numeros, 6)
print(f"Números seleccionados: {seleccionados}")

Números seleccionados: [35, 6, 38, 28, 3, 2]


In [7]:
colores = ['rojo', 'azul', 'verde']
seleccion = random.choices(colores, k=5)
print(f"Colores seleccionados: {seleccion}")

Colores seleccionados: ['rojo', 'rojo', 'rojo', 'verde', 'verde']


In [2]:

valor = random.gauss(mu=0, sigma=1)
print(f"Valor con distribución normal (media=0, desv=1): {valor}")

Valor con distribución normal (media=0, desv=1): -0.38907038515701686


In [6]:
random.seed(42)
print(random.randint(1, 10)) 

2


Otra librería: scipy

In [3]:
from scipy import linalg
import numpy as np

# Resolver Ax = b
A = np.array([[3, 2], [1, 4]])
b = np.array([6, 5])
x = linalg.solve(A, b)

print(f"Solución: x = {x}")


Solución: x = [1.4 0.9]


In [4]:
from scipy.optimize import minimize

def f(x):
    return x[0]**2 + x[1]**2 + 3

res = minimize(f, x0=[1, 1])
print(f"Mínimo encontrado en: {res.x}, valor mínimo: {res.fun}")

Mínimo encontrado en: [-2.37910001e-08 -2.37910001e-08], valor mínimo: 3.0000000000000013


In [5]:
from scipy import integrate

# Integrar f(x) = x^2 de 0 a 1
result, error = integrate.quad(lambda x: x**2, 0, 1)

print(f"Resultado de la integral: {result}, Error estimado: {error}")

Resultado de la integral: 0.33333333333333337, Error estimado: 3.700743415417189e-15
